### ISSUE TITLE
Printing params with .po files

### ISSUE THREAD

**Issue by lordmilutin** [biesbjerg/ng2-translate-po-loader#1]
Hello, I have setup ng2-translate to work with this po loader.

And it's working fine if I have no parameters for string. But in my .po files I often have something like this:

```msgid "Add %s"
msgstr "%s hinzufügen"```

How can I print that out with call from ng2-translate?
How to include plurals?

**Comment by biesbjerg** [comment]
Ng2-translate is using simple key/value strings, so there's no way to support for plurals. You will have to handle that by having multiple strings (for single/plural) in your code instead.
